version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - HEADLESS=False
    # Increase shared memory size to prevent Chrome crashes
    shm_size: '2gb'
    restart: unless-stopped
